-ifndef('__LOG_H__').
-define('__LOG_H__', true).

-ifdef(debug).
    -define(log(F, D), lager:info(F,D)).
    -define(log(F), lager:info(F)).
    -define(log_trace(F, D), lager:info(F,D)).
    -define(log_trace(F), lager:info(F)).
    -define(log_warning(F, D), lager:warning(F,D)).
    -define(log_warning(F), lager:warning(F)).
    -define(log_error(F, D), lager:error(F,D)).
    -define(log_error(F), lager:error(F)).
    -define(debug(F, D), lager:debug(F,D)).
    -define(debug(F), lager:debug(F)).
-else.
-define(IFDEBUG,false).
-ifdef(debug_log).
    -define(log(F, D), lager:info(F,D)).
    -define(log(F), lager:info(F)).
    -define(log_trace(F, D), lager:info(F,D)).
    -define(log_trace(F), lager:info(F)).
    -define(log_warning(F, D), lager:warning(F,D)).
    -define(log_warning(F), lager:warning(F)).
    -define(log_error(F, D), lager:error(F,D)).
    -define(log_error(F), lager:error(F)).
    -define(debug(F, D), lager:debug(F,D)).
    -define(debug(F), lager:debug(F)).
-else.
    -define(log(F, D), lager:info(F,D)).
    -define(log(F), lager:info(F)).
    -define(log_trace(F, D), lager:info(F,D)).
    -define(log_trace(F), lager:info(F)).
    -define(log_warning(F, D), lager:warning(F,D)).
    -define(log_warning(F), lager:warning(F)).
    -define(log_error(F, D), lager:error(F,D)).
    -define(log_error(F), lager:error(F)).
    -define(debug(F, D), ok).
    -define(debug(F), ok).
-endif.
-endif.

-endif. %% -ifndef('__LOG_H__').


