// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Bridge 管理 Erlang ERTS 子进程的生命周期与 TCP 通信。
 * 实现 Wails v3 Service 接口: ServiceStartup / ServiceShutdown。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Call 发起一次同步 RPC 到 Erlang 大脑, 返回 result。
 */
export function Call(method: string, args: { [_ in string]?: any } | null): $CancellablePromise<any> {
    return $Call.ByID(2715008145, method, args);
}

/**
 * Start 拉起 Erlang ERTS 子进程, 并与 panel_server 建立 TCP 连接。
 * ctx 来自 Wails 应用上下文, ctx 取消时子进程会被 kill。
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(2349675895);
}

/**
 * Stop 优雅停止 Erlang 子进程。
 * 优先用 rpc stop (走 TCP, 触发 Erlang init:stop), 失败 fallback 到 ctx cancel + Kill。
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2678594013);
}
