// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Bridge 管理 Wails ↔ Erlang panel_server 的 TCP/UDS 连接池。
 * 实现 Wails v3 Service 接口: ServiceStartup / ServiceShutdown。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Call 发起一次同步 RPC 到 Erlang 大脑, 返回 result。
 * @param {string} method
 * @param {{ [_ in string]?: any }} args
 * @returns {$CancellablePromise<any>}
 */
export function Call(method, args) {
    return $Call.ByID(2715008145, method, args);
}

/**
 * Start 发现 panel_server 地址并建立 TCP/UDS 连接池。
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(2349675895);
}

/**
 * Stop 优雅停止连接池。
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(2678594013);
}
