// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HermesService 暴露给 Wails 前端的 RPC；所有面板流量经 Router 转发到 Erlang。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} reqID
 * @param {boolean} allow
 * @returns {$CancellablePromise<void>}
 */
export function ApproveToolCall(reqID, allow) {
    return $Call.ByID(3392263074, reqID, allow);
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function BrainStatus(sessionID) {
    return $Call.ByID(2075847775, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<boolean>}
 */
export function DeleteSession(sessionID) {
    return $Call.ByID(845118776, sessionID);
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.HistoryEntry[]>}
 */
export function GetHistory(sessionID) {
    return $Call.ByID(3702214731, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ToolDesc[]>}
 */
export function ListTools() {
    return $Call.ByID(541722566).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} sessionID
 * @param {string} message
 * @returns {$CancellablePromise<$models.SendResult | null>}
 */
export function Send(sessionID, message) {
    return $Call.ByID(1084921369, sessionID, message).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {$models.SessionStartRequest} req
 * @returns {$CancellablePromise<$models.SessionInfo | null>}
 */
export function StartSession(req) {
    return $Call.ByID(3191461447, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopBrain() {
    return $Call.ByID(3860695757);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.HistoryEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.ToolDesc.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.SendResult.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.SessionInfo.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
