// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HermesService 是暴露给前端 (TS via Wails bindings) 的 RPC 对象。
 * 前端调用这些方法 → 经 brain.Bridge.Call (TCP+JSON) → Erlang panel_server。
 * 
 * 设计原则: 本 Service 不持有业务状态, 仅做转发。
 * 所有状态在 Erlang 侧的 agent_fsm / state_store 中, Wails 保持"哑终端"属性。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApproveToolCall 对需要人工确认的工具调用进行授权 (inline approval)。
 * @param {string} reqID
 * @param {boolean} allow
 * @returns {$CancellablePromise<void>}
 */
export function ApproveToolCall(reqID, allow) {
    return $Call.ByID(3392263074, reqID, allow);
}

/**
 * BrainStatus 返回 Erlang 大脑的运行状态。
 * 返回字段: state (idle/thinking/acting), loop_count, max_loops, history_len。
 * @param {string} sessionID
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function BrainStatus(sessionID) {
    return $Call.ByID(2075847775, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ListTools 列出 Eion-tools 侧注册的工具描述 (经 Erlang 转发)。
 * @returns {$CancellablePromise<string[]>}
 */
export function ListTools() {
    return $Call.ByID(541722566).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Send 向指定会话发送用户消息, 触发 ReAct 循环。
 * 当前是同步等待 final answer 返回 (后续可改 stream)。
 * @param {string} sessionID
 * @param {string} message
 * @returns {$CancellablePromise<$models.SendResult | null>}
 */
export function Send(sessionID, message) {
    return $Call.ByID(1084921369, sessionID, message).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * StartSession 启动一个新的 Agent 会话, Erlang 侧会派发一个 Agent_FSM 进程。
 * systemPrompt: 系统提示词 (定义 agent 角色/约束), 可为空使用默认值。
 * @param {string} systemPrompt
 * @returns {$CancellablePromise<$models.SessionInfo | null>}
 */
export function StartSession(systemPrompt) {
    return $Call.ByID(3191461447, systemPrompt).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * StopBrain 优雅停止 Erlang 大脑 (触发 init:stop, 退出整个 erl 子进程)。
 * 用于面板"退出"按钮, 让 Erlang 侧的 sup 逆序 terminate 子进程后再退。
 * @returns {$CancellablePromise<void>}
 */
export function StopBrain() {
    return $Call.ByID(3860695757);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $models.SendResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.SessionInfo.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
