// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HermesService 是暴露给前端 (TS via Wails bindings) 的 RPC 对象。
 * 前端调用这些方法 → 经 brain.Bridge.Call (TCP+JSON) → Erlang panel_server。
 * 
 * 设计原则: 本 Service 不持有业务状态, 仅做转发。
 * 所有状态在 Erlang 侧的 agent_fsm / state_store 中, Wails 保持"哑终端"属性。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApproveToolCall 对需要人工确认的工具调用进行授权 (inline approval)。
 */
export function ApproveToolCall(reqID: string, allow: boolean): $CancellablePromise<void> {
    return $Call.ByID(3392263074, reqID, allow);
}

/**
 * BrainStatus 返回 Erlang 大脑的运行状态。
 * 返回字段: state (idle/thinking/acting), loop_count, max_loops, history_len。
 */
export function BrainStatus(sessionID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2075847775, sessionID);
}

/**
 * ListTools 列出 Eion-tools 侧注册的工具描述 (经 Erlang 转发)。
 */
export function ListTools(): $CancellablePromise<string[] | null> {
    return $Call.ByID(541722566);
}

/**
 * Send 向指定会话发送用户消息, 触发 ReAct 循环。
 * 当前是同步等待 final answer 返回 (后续可改 stream)。
 */
export function Send(sessionID: string, message: string): $CancellablePromise<$models.SendResult | null> {
    return $Call.ByID(1084921369, sessionID, message);
}

/**
 * StartSession 启动一个新的 Agent 会话, Erlang 侧会派发一个 Agent_FSM 进程。
 * systemPrompt: 系统提示词 (定义 agent 角色/约束), 可为空使用默认值。
 */
export function StartSession(systemPrompt: string): $CancellablePromise<$models.SessionInfo | null> {
    return $Call.ByID(3191461447, systemPrompt);
}

/**
 * StopBrain 优雅停止 Erlang 大脑 (触发 init:stop, 退出整个 erl 子进程)。
 * 用于面板"退出"按钮, 让 Erlang 侧的 sup 逆序 terminate 子进程后再退。
 */
export function StopBrain(): $CancellablePromise<void> {
    return $Call.ByID(3860695757);
}
