// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SendResult: Send 返回值
 */
export class SendResult {
    /**
     * Creates a new SendResult instance.
     * @param {Partial<SendResult>} [$$source = {}] - The source object to create the SendResult.
     */
    constructor($$source = {}) {
        if (!("stream_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stream_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SendResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SendResult(/** @type {Partial<SendResult>} */($$parsedSource));
    }
}

/**
 * SessionInfo: StartSession 返回值
 */
export class SessionInfo {
    /**
     * Creates a new SessionInfo instance.
     * @param {Partial<SessionInfo>} [$$source = {}] - The source object to create the SessionInfo.
     */
    constructor($$source = {}) {
        if (!("session_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["session_id"] = "";
        }
        if (!("started" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["started"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionInfo(/** @type {Partial<SessionInfo>} */($$parsedSource));
    }
}
