// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class HistoryEntry {
    /**
     * Creates a new HistoryEntry instance.
     * @param {Partial<HistoryEntry>} [$$source = {}] - The source object to create the HistoryEntry.
     */
    constructor($$source = {}) {
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ToolCall[] | undefined}
             */
            this["tool_calls"] = undefined;
        }
        if (!("tool_call_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tool_call_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HistoryEntry}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tool_calls" in $$parsedSource) {
            $$parsedSource["tool_calls"] = $$createField2_0($$parsedSource["tool_calls"]);
        }
        return new HistoryEntry(/** @type {Partial<HistoryEntry>} */($$parsedSource));
    }
}

export class SendResult {
    /**
     * Creates a new SendResult instance.
     * @param {Partial<SendResult>} [$$source = {}] - The source object to create the SendResult.
     */
    constructor($$source = {}) {
        if (!("stream_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stream_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SendResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SendResult(/** @type {Partial<SendResult>} */($$parsedSource));
    }
}

export class SessionInfo {
    /**
     * Creates a new SessionInfo instance.
     * @param {Partial<SessionInfo>} [$$source = {}] - The source object to create the SessionInfo.
     */
    constructor($$source = {}) {
        if (!("session_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["session_id"] = "";
        }
        if (!("started" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["started"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionInfo(/** @type {Partial<SessionInfo>} */($$parsedSource));
    }
}

export class SessionStartRequest {
    /**
     * Creates a new SessionStartRequest instance.
     * @param {Partial<SessionStartRequest>} [$$source = {}] - The source object to create the SessionStartRequest.
     */
    constructor($$source = {}) {
        if (!("system_prompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["system_prompt"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("api_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_key"] = "";
        }
        if (!("api_base" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_base"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionStartRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionStartRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionStartRequest(/** @type {Partial<SessionStartRequest>} */($$parsedSource));
    }
}

export class ToolCall {
    /**
     * Creates a new ToolCall instance.
     * @param {Partial<ToolCall>} [$$source = {}] - The source object to create the ToolCall.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("function" in $$source)) {
            /**
             * @member
             * @type {ToolFunction}
             */
            this["function"] = (new ToolFunction());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCall instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolCall}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("function" in $$parsedSource) {
            $$parsedSource["function"] = $$createField2_0($$parsedSource["function"]);
        }
        return new ToolCall(/** @type {Partial<ToolCall>} */($$parsedSource));
    }
}

export class ToolDesc {
    /**
     * Creates a new ToolDesc instance.
     * @param {Partial<ToolDesc>} [$$source = {}] - The source object to create the ToolDesc.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["parameters"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolDesc instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolDesc}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolDesc(/** @type {Partial<ToolDesc>} */($$parsedSource));
    }
}

export class ToolFunction {
    /**
     * Creates a new ToolFunction instance.
     * @param {Partial<ToolFunction>} [$$source = {}] - The source object to create the ToolFunction.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["arguments"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolFunction instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolFunction}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolFunction(/** @type {Partial<ToolFunction>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ToolCall.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ToolFunction.createFrom;
