// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * HistoryEntry 单条对话历史 (与 panel.proto HistoryEntry 对齐)
 */
export class HistoryEntry {
    /**
     * Creates a new HistoryEntry instance.
     * @param {Partial<HistoryEntry>} [$$source = {}] - The source object to create the HistoryEntry.
     */
    constructor($$source = {}) {
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("tool_calls_json" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tool_calls_json"] = "";
        }
        if (!("tool_call_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tool_call_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HistoryEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryEntry(/** @type {Partial<HistoryEntry>} */($$parsedSource));
    }
}

/**
 * SendResult: Send 返回值
 */
export class SendResult {
    /**
     * Creates a new SendResult instance.
     * @param {Partial<SendResult>} [$$source = {}] - The source object to create the SendResult.
     */
    constructor($$source = {}) {
        if (!("stream_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stream_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SendResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SendResult(/** @type {Partial<SendResult>} */($$parsedSource));
    }
}

/**
 * SessionInfo: StartSession 返回值
 */
export class SessionInfo {
    /**
     * Creates a new SessionInfo instance.
     * @param {Partial<SessionInfo>} [$$source = {}] - The source object to create the SessionInfo.
     */
    constructor($$source = {}) {
        if (!("session_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["session_id"] = "";
        }
        if (!("started" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["started"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionInfo(/** @type {Partial<SessionInfo>} */($$parsedSource));
    }
}

/**
 * SessionStartRequest 新建会话参数 (模型/凭证可按会话覆盖 app env)
 */
export class SessionStartRequest {
    /**
     * Creates a new SessionStartRequest instance.
     * @param {Partial<SessionStartRequest>} [$$source = {}] - The source object to create the SessionStartRequest.
     */
    constructor($$source = {}) {
        if (!("system_prompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["system_prompt"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("api_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_key"] = "";
        }
        if (!("api_base" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_base"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionStartRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionStartRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionStartRequest(/** @type {Partial<SessionStartRequest>} */($$parsedSource));
    }
}

/**
 * ToolDesc 工具描述 (与 panel.proto ListToolsResult 对齐)
 */
export class ToolDesc {
    /**
     * Creates a new ToolDesc instance.
     * @param {Partial<ToolDesc>} [$$source = {}] - The source object to create the ToolDesc.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("parameters_json" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parameters_json"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolDesc instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolDesc}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolDesc(/** @type {Partial<ToolDesc>} */($$parsedSource));
    }
}
