// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SendResult: Send 返回值
 */
export interface SendResult {
    "stream_id": string;
}

/**
 * SessionInfo: StartSession 返回值
 */
export interface SessionInfo {
    "session_id": string;
    "started": boolean;
}
