// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * EionExecutor 绑定进程内 Eion-tools server，经 panel exec 帧执行 LLM/工具。
 */
export class EionExecutor {
    /**
     * Creates a new EionExecutor instance.
     * @param {Partial<EionExecutor>} [$$source = {}] - The source object to create the EionExecutor.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EionExecutor instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EionExecutor}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EionExecutor(/** @type {Partial<EionExecutor>} */($$parsedSource));
    }
}

/**
 * StreamHub 按事件类型分流 panel stream。
 * 
 * 规则 (与架构约定一致):
 *   - chunk / tool_event → 仅面板 (低延迟预览)
 *   - final / error      → 面板 (Erlang 在 push_final 前已落 history)
 * 
 * Phase C 可在 final 上增加 brain 侧 in-process ack 回调。
 */
export class StreamHub {
    /**
     * Creates a new StreamHub instance.
     * @param {Partial<StreamHub>} [$$source = {}] - The source object to create the StreamHub.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamHub instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StreamHub}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamHub(/** @type {Partial<StreamHub>} */($$parsedSource));
    }
}
