// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Router 统一面板 ↔ 大脑 ↔ 流式分发的 Go 侧入口。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as server$0 from "../../../github.com/light-code-ai/eion-tools/pkg/server/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as brain$0 from "../brain/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AttachEion 在 embedded Eion 启动后注入 (Phase B 入口)。
 * @param {server$0.Server | null} srv
 * @returns {$CancellablePromise<void>}
 */
export function AttachEion(srv) {
    return $Call.ByID(1796779862, srv);
}

/**
 * Bridge 返回底层 panel 连接池 (生命周期仍由 Wails Service 管理)。
 * @returns {$CancellablePromise<brain$0.Bridge | null>}
 */
export function Bridge() {
    return $Call.ByID(2700888325).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CallPanel 转发 RPC 到 Erlang panel_server。
 * @param {string} method
 * @param {{ [_ in string]?: any }} args
 * @returns {$CancellablePromise<any>}
 */
export function CallPanel(method, args) {
    return $Call.ByID(2674710958, method, args);
}

/**
 * Eion 返回进程内执行器 (可能未就绪)。
 * @returns {$CancellablePromise<$models.EionExecutor | null>}
 */
export function Eion() {
    return $Call.ByID(2472716411).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SetStreamTap 追加 stream 监听 (e2e/调试); 在 Hub 分流之后调用。
 * @param {any} fn
 * @returns {$CancellablePromise<void>}
 */
export function SetStreamTap(fn) {
    return $Call.ByID(2268196261, fn);
}

/**
 * StreamHub 返回流式分发器 (测试/扩展用)。
 * @returns {$CancellablePromise<$models.StreamHub | null>}
 */
export function StreamHub() {
    return $Call.ByID(2115899631).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

// Private type creation functions
const $$createType0 = brain$0.Bridge.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.EionExecutor.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.StreamHub.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
