// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Embedded 实现 Wails Service 生命周期，在 UI 启动前拉起 loopback listener。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as server$0 from "../../../github.com/light-code-ai/eion-tools/pkg/server/models.js";

/**
 * Server 返回已启动的 embedded 实例 (未启动时为 nil)。
 * @returns {$CancellablePromise<server$0.Server | null>}
 */
export function Server() {
    return $Call.ByID(1905974352).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = server$0.Server.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
